# Generated by Django 4.2.5 on 2023-09-18 01:28

import contents.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(unique=True, verbose_name='생성시간')),
                ('content', models.TextField(verbose_name='방명록')),
            ],
        ),
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='부스이름')),
                ('date', models.DateField(choices=[('day1', datetime.datetime(2023, 10, 4, 0, 0)), ('day2', datetime.datetime(2023, 10, 5, 0, 0)), ('day3', datetime.datetime(2023, 10, 6, 0, 0))], default='day1', verbose_name='부스날짜')),
                ('introduce', models.TextField(verbose_name='한줄소개')),
                ('notice', models.TextField(verbose_name='공지사항')),
                ('image', models.ImageField(blank=True, null=True, upload_to='booth-image', verbose_name='부스 사진')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='대학 커스텀 ID')),
                ('college', models.CharField(default='인문대학', max_length=30, verbose_name='단과대학명')),
                ('total', models.IntegerField(verbose_name='총인원')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[contents.models.validate_stu_id], verbose_name='학번')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.college', verbose_name='소속단과대학')),
            ],
        ),
    ]
