# Generated by Django 4.2.5 on 2023-09-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='date',
            field=models.CharField(choices=[('day1', '2023-10-04'), ('day2', '2023-10-05'), ('day3', '2023-10-06')], default='day1', max_length=10, verbose_name='부스날짜'),
        ),
    ]
