# Generated by Django 4.2.5 on 2023-09-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_remove_booth_notice_booth_category_booth_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='id',
        ),
        migrations.AddField(
            model_name='booth',
            name='booth_id',
            field=models.CharField(default='10401', max_length=10, primary_key=True, serialize=False, verbose_name='부스 커스텀 ID'),
        ),
    ]
