# Generated by Django 4.2.5 on 2023-09-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0006_alter_booth_booth_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="booth_id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="부스 커스텀 ID"
            ),
        ),
    ]
